### ISSUE TITLE
RVM fails to work properly if the .rvmrc is checked in

### ISSUE THREAD

**Issue by skizz** [srushti/goldberg#136] opened 2012-06-20 22:31 UTC
According to RVM's documentation it is a best practice to check in your .rvmrc file.

(See number 2: https://rvm.io/rvm/best-practices/)

If you do this, then Goldberg tries to use its own rvm settings (goldberg-projectname) which is incorrect. Bundler is not installed and the build fails with the error "Bundler gem is not installed"

If the project is new, you need to login to the server and cd into the build directory and do a manual rvm gemset create/gem install bundler to fix this.

**Comment by srushti** [comment] 2012-06-24 06:01
True. This is related to #89 because, ideally, Goldberg should be installing Bundler in the new gemset it's creating (which seems to be broken now).

Even if Goldberg honoured the checked in .rvmrc (which would mean you don't have to duplicate the ruby version in the goldberg_config.rb file) the lack of a Bundler install still means it's broken. We'll look into it now.

**Comment by srushti** [comment] 2012-07-24 11:56
@skizz Like I said earlier, Goldberg is currently designed not to look at the project's own .rvmrc at all (irrespective of best practices). Instead it looks at goldberg_config to figure out what ruby you want to use. Having used that ruby (or the default ruby if nothing is specified) and the gemset "goldberg-projectname" it is meant to install bundler (if it doesn't already exist) and then start the build.

It looks like the installation of bundler here was broken. Could you verify that with the latest the bundler gem itself is being installed? If that's the case, please use the goldberg_config.rb file to set the ruby you wish to use. Then, I'll create another issue for goldberg to look for a .rvmrc first, and if it doesn't find it, to use the ruby from goldberg_config, and close this issue.

**Comment by srushti** [comment] 2012-07-30 12:00
I'm not able to reproduce the issue with the Bundler gem (it did exist before, but looks like it's been fixed now). I've created #140 to cover the scenario of .rvmrc being ignored. As of now, you have to specify your Ruby in two places, but you shouldn't have to do your logging in to the server work.

As always, please let me know if this issue is still reproducible for you.

**Closed as completed by srushti** 2012-07-30 12:00 UTC
Labels: Bug
