### ISSUE TITLE
Poller Error "cannot start a transaction within a transaction"

### ISSUE THREAD

**Issue by pagerc** [srushti/goldberg#131] opened 2012-03-22 14:54 UTC
["/usr/local/rvm/gems/ruby-1.9.3-p125/gems/sqlite3-1.3.5/lib/sqlite3/database.rb:97:in `close'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/sqlite3-1.3.5/lib/sqlite3/database.rb:97:in`ensure in prepare'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/sqlite3-1.3.5/lib/sqlite3/database.rb:97:in `prepare'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/sqlite3-1.3.5/lib/sqlite3/database.rb:134:in`execute'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/sqlite3-1.3.5/lib/sqlite3/database.rb:484:in `transaction'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/connection_adapters/sqlite_adapter.rb:295:in`begin_db_transaction'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:184:in `transaction'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/transactions.rb:208:in`transaction'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/transactions.rb:241:in`block in save'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/transactions.rb:240:in`save'",
 "/opt/goldberg/app/models/project.rb:76:in `run_build'",
 "/opt/goldberg/app/models/init.rb:29:in`block in poll'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/relation.rb:15:in `each'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.1.1/lib/active_record/relation.rb:15:in`each'",
 "/opt/goldberg/app/models/init.rb:27:in `poll'",
 "/opt/goldberg/app/models/init.rb:39:in`start_poller'",
 "/opt/goldberg/bin/goldberg:41:in `block (2 levels) in <main>'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/commander-4.0.7/lib/commander/command.rb:180:in`call'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/commander-4.0.7/lib/commander/command.rb:180:in `call'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/commander-4.0.7/lib/commander/command.rb:155:in`run'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/commander-4.0.7/lib/commander/runner.rb:402:in `run_active_command'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/commander-4.0.7/lib/commander/runner.rb:66:in`run!'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/commander-4.0.7/lib/commander/delegates.rb:11:in `run!'",
 "/usr/local/rvm/gems/ruby-1.9.3-p125/gems/commander-4.0.7/lib/commander/import.rb:10:in`block in <top (required)>'"]

**Comment by srushti** [comment] 2012-03-28 11:22
This seems to only happen on 1.9.3. And certainly needs to get fixed.

**Comment by pahnin** [comment] 2012-06-22 02:04
How to check this? I mean my system has ruby 1.9.3 installed but I think it uses 1.9.1 while running goldberg!
Give me some instructions and I can run goldberg on Virtualmachine

**Comment by srushti** [comment] 2012-06-24 05:57
You don't need a Virtualmachine. Basically, you need to make sure you're starting goldberg in 1.9.3. Just make sure that running 'ruby -v' on your prompt (just before you start goldberg) gives you something like 'ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]'. After that if you force a build you get this error.

**Comment by pahnin** [comment] 2012-06-24 13:30
My ruby -v
returns this ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
its also shown while rails server starts

=> Booting WEBrick
=> Rails 3.2.6 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2012-06-24 18:59:20] INFO  WEBrick 1.3.1
[2012-06-24 18:59:20] INFO  ruby 1.9.3 (2012-04-20) [x86_64-linux]
[2012-06-24 18:59:20] INFO  WEBrick::HTTPServer#start: pid=22238 port=3000

So, I confirm that this error does not show up in every 1.9.3 installations

Thanks

**Comment by pahnin** [comment] 2012-06-25 18:43
I confirm that my poller is running and I get no error while force build except error from build itself, because it coudnt install lib-xml and its not related to poller

**Comment by srushti** [comment] 2012-06-26 11:17
@pahnin Sure, that means you can't reproduce this issue. Leave this alone, and I'll try and get to it soon.

**Comment by srushti** [comment] 2012-07-18 13:51
I can't reproduce this issue either, and I was able to in the past. It looks like this has somehow quietly fixed itself. I'm closing this. @pagerc please let me know if this is still occurring for you.

**Closed as completed by srushti** 2012-07-18 13:51 UTC
Labels: Bug
